'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace ExportAspControlsViaReports


	Partial Public Class WebForm1

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxGridView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' WebChartControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected WebChartControl1 As Global.DevExpress.XtraCharts.Web.WebChartControl

		''' <summary>
		''' Button1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Button1 As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' ASPxGridViewExporter1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

		''' <summary>
		''' ObjectDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource
	End Class
End Namespace
